<a href="https://colab.research.google.com/github/Junhyuck123/Production-control/blob/main/Final_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy.optimize import linear_sum_assignment

c_m = np.array([[9,6,3,4],
                [5,8,12,10],
                [2,6,7,4],
                [4,11,13,7]])
row_ind, col_ind = linear_sum_assignment(c_m)
opt_ass = col_ind
tc = c_m[row_ind, col_ind].sum()


print(c_m)
print(opt_ass)
print(tc)

[[ 9  6  3  4]
 [ 5  8 12 10]
 [ 2  6  7  4]
 [ 4 11 13  7]]
[2 1 3 0]
19


In [ ]:
import numpy as np
import pandas as pd
!pip install pulp
import pulp

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# V1

In [ ]:
#n = int(input())
n =4

In [ ]:
job = []
resource = []
for i in range(n):
  job.append("J{}".format(i))
  resource.append("R{}".format(i))

for i in range(n):
  globals()["Col{}".format(i)] = []
  globals()["Low{}".format(i)] = []

In [ ]:
# c = np.random.randint(1, 15, size = (n, n))
# cost = pd.DataFrame(c, index = job, columns = resource)
# cost
cost = pd.DataFrame(c_m, index = job, columns = resource)
cost



R0  R1  R2  R3
J0   9   6   3   4
J1   5   8  12  10
J2   2   6   7   4
J3   4  11  13   7

In [ ]:
stack_c = pd.DataFrame()
for i in range(n):
  col = np.array(cost['R{}'.format(i)])
  col_min = min(col)
  col = col - col_min
  col = pd.DataFrame(col)
  stack_c[i] = col
stack_c

0  1   2  3
0  7  0   0  0
1  3  2   9  6
2  0  0   4  0
3  2  5  10  3

In [ ]:
stack_r = pd.DataFrame()
for i in range(n):
  row = stack_c.iloc[i][:]
  row_min = min(row)
  row = row - row_min
  row = pd.DataFrame(row)
  stack_r[i] = row
stack_r = stack_r.transpose()
stack_r

0  1  2  3
0  7  0  0  0
1  1  0  7  4
2  0  0  4  0
3  0  3  8  1

In [ ]:
count_col = 0
count_col_lst = []
for i in range(n):
  for j in range(n):
    if(stack_r.iloc[i][j] == 0):
      count_col += 1

  globals()["Zero_cnt_col{}".format(i)] = count_col
  count_col_lst.append(int(count_col))
  count_col = 0


count_row = 0
count_row_lst = []
for i in range(n):
  for j in range(n):
    if(stack_r.iloc[j][i] == 0):
      count_row += 1

  globals()["Zero_cnt_row{}".format(i)] = count_row
  count_row_lst.append(int(count_row))
  count_row = 0


print('row의 0의 수 : {}'.format(count_row_lst))
print('col의 0의 수 : {}'.format(count_col_lst))

row의 0의 수 : [2, 3, 1, 2]
col의 0의 수 : [3, 1, 3, 1]


In [ ]:
row_zero_index = [i for i, value in enumerate(count_row_lst) if value == np.max(count_row_lst)]
col_zero_index = [i for i, value in enumerate(count_col_lst) if value == np.max(count_col_lst)]

choice = []
choice.append(int(np.max(count_row_lst)))
choice.append(int(np.max(count_col_lst)))
choice = int(np.argmax(choice))
print('row의 0의 수 Max값 : {}'.format(np.max(count_row_lst)))
print('col의 0의 수 Max값 : {}'.format(np.max(count_col_lst)))
print('row의 0의 수 Max값 index : {}'.format(np.max(row_zero_index)))
print('col의 0의 수 Max값 index : {}'.format(np.max(col_zero_index)))

if(choice == 0):
  choice_str = "행"
else:
  choice_str = "열"
print('삭제할 곳 선택 : {}'.format(choice_str))

row의 0의 수 Max값 : 3
col의 0의 수 Max값 : 3
row의 0의 수 Max값 index : 1
col의 0의 수 Max값 index : 2
삭제할 곳 선택 : 행


In [ ]:
if(choice == 0):
  result_step1 = stack_r.drop(row_zero_index[0], axis='columns')
else:
  result_step1 = stack_r.drop(columns=col_zero_index[0])
result_step1= pd.DataFrame(np.array(result_step1))
result_step1

0  1  2
0  7  0  0
1  1  7  4
2  0  4  0
3  0  8  1

In [ ]:
count_col = 0
count_col_lst = []
for i in range(len(result_step1.index)):
  for j in range(len(result_step1.columns)):
    if(int(result_step1.iloc[i][j]) == 0):
      count_col += 1
  globals()["Zero_cnt_col{}".format(i)] = count_col
  count_col_lst.append(int(count_col))
  count_col = 0

count_row = 0
count_row_lst = []
for i in range(len(result_step1.columns)):
  for j in range(len(result_step1.index)):
    if(int(result_step1.iloc[j][i]) == 0):
      count_row += 1

  globals()["Zero_cnt_row{}".format(i)] = count_row
  count_row_lst.append(int(count_row))
  count_row = 0


In [ ]:
row_zero_index = [i for i, value in enumerate(count_row_lst) if value == np.max(count_row_lst)]
col_zero_index = [i for i, value in enumerate(count_col_lst) if value == np.max(count_col_lst)]

choice = []
choice.append(int(np.max(count_row_lst)))
choice.append(int(np.max(count_col_lst)))
choice = int(np.argmax(choice))
np.max(count_row_lst),np.max(count_col_lst), choice

(2, 2, 0)

In [ ]:
count_row_lst, count_col_lst 

([2, 1, 2], [2, 0, 2, 1])

In [ ]:
choice

0

In [ ]:
if(choice == 0):
  result_step2 = result_step1.drop(row_zero_index[0], axis='columns')
else:
  result_step2 = result_step1.drop(columns=col_zero_index[0])


In [ ]:
result_step2

1  2
0  0  0
1  7  4
2  4  0
3  8  1

In [ ]:
result_step2= pd.DataFrame(np.array(result_step2))

In [ ]:
result_step2

0  1
0  0  0
1  7  4
2  4  0
3  8  1

In [ ]:
count_col = 0
count_col_lst = []
for i in range(len(result_step2.index)):
  for j in range(len(result_step2.columns)):
    if(int(result_step2.iloc[i][j]) == 0):
      count_col += 1
  globals()["Zero_cnt_col{}".format(i)] = count_col
  count_col_lst.append(int(count_col))
  count_col = 0

count_row = 0
count_row_lst = []
for i in range(len(result_step2.columns)):
  for j in range(len(result_step2.index)):
    if(int(result_step2.iloc[j][i]) == 0):
      count_row += 1

  globals()["Zero_cnt_row{}".format(i)] = count_row
  count_row_lst.append(int(count_row))
  count_row = 0


In [ ]:
row_zero_index = [i for i, value in enumerate(count_row_lst) if value == np.max(count_row_lst)]
col_zero_index = [i for i, value in enumerate(count_col_lst) if value == np.max(count_col_lst)]

choice = []
choice.append(int(np.max(count_row_lst)))
choice.append(int(np.max(count_col_lst)))
choice = int(np.argmax(choice))
np.max(count_row_lst),np.max(count_col_lst), choice

(2, 2, 0)

In [ ]:
count_row_lst, count_col_lst 

([1, 2], [2, 0, 1, 0])

In [ ]:
choice

0

In [ ]:
if(choice == 0):
  result_step3 = result_step2.drop(row_zero_index[0], axis='columns')
else:
  result_step3 = result_step2.drop(columns=col_zero_index[0])


In [ ]:
result_step3

0
0  0
1  7
2  4
3  8

## 3

In [ ]:
count_col = 0
count_col_lst = []
for i in range(len(result_step3.index)):
  for j in range(len(result_step3.columns)):
    if(int(result_step3.iloc[i][j]) == 0):
      count_col += 1
  globals()["Zero_cnt_col{}".format(i)] = count_col
  count_col_lst.append(int(count_col))
  count_col = 0

count_row = 0
count_row_lst = []
for i in range(len(result_step3.columns)):
  for j in range(len(result_step3.index)):
    if(int(result_step3.iloc[j][i]) == 0):
      count_row += 1

  globals()["Zero_cnt_row{}".format(i)] = count_row
  count_row_lst.append(int(count_row))
  count_row = 0


In [ ]:
row_zero_index = [i for i, value in enumerate(count_row_lst) if value == np.max(count_row_lst)]
col_zero_index = [i for i, value in enumerate(count_col_lst) if value == np.max(count_col_lst)]

choice = []
choice.append(int(np.max(count_row_lst)))
choice.append(int(np.max(count_col_lst)))
choice = int(np.argmax(choice))
np.max(count_row_lst),np.max(count_col_lst), choice

(1, 1, 0)

In [ ]:
count_row_lst, count_col_lst 

([1], [1, 0, 0, 0])

In [ ]:
choice

0

In [ ]:
if(choice == 0):
  result_step4 = result_step3.drop(row_zero_index[0], axis='columns')
else:
  result_step4 = result_step3.drop(columns=col_zero_index[0])


In [ ]:
result_step4

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

# V2

In [ ]:
stack_r1 = pd.DataFrame()
stack_r1 = stack_r.copy()
del_row_lst = [] # 삭제한 행 목록
del_col_lst = [] # 삭제한 열 목록
row_cnt = 0 # 행에서 0의 갯수
col_cnt = 0 # 열에서 0의 갯수
cnt = 0 # For 루프 시행 횟수

In [ ]:
try: # n번의 시행중 시행횟수가 일치하지 않을 시 오류취급 for 루프 중단
  for d in range(n): # n matrix의 경우 n번 시행
    count_col = 0 # col의 index별 0의갯수 초기화
    count_col_lst = [] # 열 별 0의 갯수 저장
    for i in range(len(stack_r1.index)):
      for j in range(len(stack_r1.columns)): # 열과 행의 갯수 만큼 for 문 실행 (삭제하며 찾기 때문에 n이 아닌 len루프)
        if(stack_r1.iloc[i][j] == 0): 
          count_col += 1

      count_col_lst.append(int(count_col))
      print('col의 0의 수 : {}'.format(count_col_lst))
      count_col = 0

    # 행에 대해서 위와 동일한 루프 (수정 필요)
    count_row = 0
    count_row_lst = []
    for i in range(len(stack_r1.columns)):
      for j in range(len(stack_r1.index)):
        if(stack_r1.iloc[j][i] == 0):
          count_row += 1

      count_row_lst.append(int(count_row))
      print('row의 0의 수 : {}'.format(count_row_lst))
      count_row = 0


    
    # Zero 개수의 최대값 index를 저장하는 리스트
    row_zero_index = [i for i, value in enumerate(count_row_lst) if value == np.max(count_row_lst)]
    col_zero_index = [i for i, value in enumerate(count_col_lst) if value == np.max(count_col_lst)]

    # 행을 삭제할지 열을 삭제할지 결정
    choice = []
    choice.append(int(np.max(count_row_lst)))
    choice.append(int(np.max(count_col_lst)))
    choice = int(np.argmax(choice)) # 같은 숫자일 경우 행을 삭제
    print('row의 0의 수 Max값 : {}'.format(np.max(count_row_lst)))
    print('col의 0의 수 Max값 : {}'.format(np.max(count_col_lst)))
    print('row의 0의 수 Max값 index : {}'.format(np.max(row_zero_index)))
    print('col의 0의 수 Max값 index : {}'.format(np.max(col_zero_index)))

    if(choice == 0):
      choice_str = "행"
    else:
      choice_str = "열"
    print('삭제할 곳 선택 : {0} {1}'.format(choice_str, np.max(row_zero_index)))  # 단순 출력


    if(choice == 0): # 행을 선택한 경우 삭제
      del_row_lst.append(row_zero_index[0])
      stack_r1 = stack_r1.drop(row_zero_index[0], axis='columns')
    else:
      del_col_lst.append(col_zero_index[0])
      stack_r1 = stack_r1.drop(columns=col_zero_index[0])

    stack_r1= pd.DataFrame(np.array(stack_r1)) #DataFrame형태로 재변환 (1열을 삭제할 경우 index가 0 2 3 으로 처리 --> for문에서 오류발생)
    cnt += 1

  if(cnt != 4):
    print("아래 항목을 실행하세요")

except:
  print("아래 항목을 실행하세요")
  # num = list(range(n))
  # del_row_index = []
  # del_col_index = []
  # for i in range(len(del_row_lst)):
  #   del_row_index.append(num[del_row_lst[i]])
  #   del num[del_row_lst[i]]
  # num = list(range(n))
  # for i in range(len(del_col_lst)):
  #   del_col_index.append(num[del_col_lst[i]])
  #   del num[del_col_lst[i]]

  # del_row_index, del_col_index    
  # for i in range(len(del_row_index)):
  #   if(len(del_col_index) >= 1):
  #     for j in range(len(del_col_index)):
  #       if(stack_r[del_row_index[i]][del_col_index[j]] == 0):
  #         stack_r[del_row_index[i]][del_col_index[j]] += 1
  # stack_r1 = stack_r.copy()

col의 0의 수 : [3]
col의 0의 수 : [3, 1]
col의 0의 수 : [3, 1, 3]
col의 0의 수 : [3, 1, 3, 1]
row의 0의 수 : [2]
row의 0의 수 : [2, 3]
row의 0의 수 : [2, 3, 1]
row의 0의 수 : [2, 3, 1, 2]
row의 0의 수 Max값 : 3
col의 0의 수 Max값 : 3
row의 0의 수 Max값 index : 1
col의 0의 수 Max값 index : 2
삭제할 곳 선택 : 행 1
col의 0의 수 : [2]
col의 0의 수 : [2, 0]
col의 0의 수 : [2, 0, 2]
col의 0의 수 : [2, 0, 2, 1]
row의 0의 수 : [2]
row의 0의 수 : [2, 1]
row의 0의 수 : [2, 1, 2]
row의 0의 수 Max값 : 2
col의 0의 수 Max값 : 2
row의 0의 수 Max값 index : 2
col의 0의 수 Max값 index : 2
삭제할 곳 선택 : 행 2
col의 0의 수 : [2]
col의 0의 수 : [2, 0]
col의 0의 수 : [2, 0, 1]
col의 0의 수 : [2, 0, 1, 0]
row의 0의 수 : [1]
row의 0의 수 : [1, 2]
row의 0의 수 Max값 : 2
col의 0의 수 Max값 : 2
row의 0의 수 Max값 index : 1
col의 0의 수 Max값 index : 0
삭제할 곳 선택 : 행 1
col의 0의 수 : [1]
col의 0의 수 : [1, 0]
col의 0의 수 : [1, 0, 0]
col의 0의 수 : [1, 0, 0, 0]
row의 0의 수 : [1]
row의 0의 수 Max값 : 1
col의 0의 수 Max값 : 1
row의 0의 수 Max값 index : 0
col의 0의 수 Max값 index : 0
삭제할 곳 선택 : 행 0


In [ ]:
f = np.array(stack_r)

In [ ]:
del_row_index = [0,1,3]
del_col_index = [1]

In [ ]:
if(cnt != 3):
  num = list(range(n))
  plus_row = list(set(num)-set(del_row_index))


  matrix_1 = np.random.randint(0, 1, size = (n, n))
  matrix_2 = np.random.randint(0, 1, size = (n, n))
  matrix = np.random.randint(1, 2, size = (n, n))
  for i in range(len(del_row_index)):
    matrix[del_row_index[i]] = 0
    for j in range(len(del_col_index)):
      matrix_1[del_row_index[i]][del_col_index[j]] = 1
      for k in range(len(plus_row)):
        matrix[plus_row[k]][del_col_index[j]] = 0
        matrix_2[plus_row[k]][del_col_index[j]] = 2

In [ ]:
f

array([[7, 0, 0, 0],
       [1, 0, 7, 4],
       [0, 0, 4, 0],
       [0, 3, 8, 1]])

In [ ]:
g = np.multiply(f, matrix)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 0]])

In [ ]:
matrix_1

array([[0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0]])

In [ ]:
matrix

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 1, 1],
       [0, 0, 0, 0]])

In [ ]:
matrix_2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
a = [0,1,2,3]
del_row_index = []
del_col_index = []
for i in range(len(del_row_lst)):
  del_row_index.append(a[del_row_lst[i]])
  del a[del_row_lst[i]]
a = [0,1,2,3]
for i in range(len(del_col_lst)):
  del_col_index.append(a[del_col_lst[i]])
  del a[del_col_lst[i]]



In [ ]:
del_row_index = []
del_col_index = []

del_row_index = [0,1,3]
del_col_index = [1]

In [ ]:
d = [0,1,2,3]

In [ ]:
plus_row = list(set(d)-set(del_row_index))

In [ ]:

print(del_row_index, del_col_index)

c = np.random.randint(1, 2, size = (n, n))

for i in range(len(del_row_index)):
  c[del_row_index[i]] = 0
  for j in range(len(del_col_index)):
    for k in range(len(plus_row)):
      c[plus_row[k]][del_col_index[j]] = 0


[0, 1, 3] [1]


In [ ]:
e = np.random.randint(1, 2, size = (n, n))

In [ ]:
# try:
#   # for i in range(n):
#   #   for j in range(n):
#   #     if(stack_r1[i][j] == 0):
#   #       cnt +=1
#   #while(len(del_row_lst)+len(del_col_lst) < n):
#   for d in range(n):
#     count_col = 0
#     count_col_lst = []
#     for i in range(len(stack_r1.index)):
#       for j in range(len(stack_r1.columns)):
#         if(stack_r1.iloc[i][j] == 0):
#           count_col += 1

#       # globals()["Zero_cnt_col{}".format(i)] = count_col
#       count_col_lst.append(int(count_col))
#       count_col = 0


#     count_row = 0
#     count_row_lst = []
#     for i in range(len(stack_r1.columns)):
#       for j in range(len(stack_r1.index)):
#         if(stack_r1.iloc[j][i] == 0):
#           count_row += 1

#       # globals()["Zero_cnt_row{}".format(i)] = count_row
#       count_row_lst.append(int(count_row))
#       count_row = 0


#     # print('row의 0의 수 : {}'.format(count_row_lst))
#     # print('col의 0의 수 : {}'.format(count_col_lst))
#     row_zero_index = [i for i, value in enumerate(count_row_lst) if value == np.max(count_row_lst)]
#     col_zero_index = [i for i, value in enumerate(count_col_lst) if value == np.max(count_col_lst)]

#     choice = []
#     choice.append(int(np.max(count_row_lst)))
#     choice.append(int(np.max(count_col_lst)))
#     choice = int(np.argmax(choice))
#     # print('row의 0의 수 Max값 : {}'.format(np.max(count_row_lst)))
#     # print('col의 0의 수 Max값 : {}'.format(np.max(count_col_lst)))
#     # print('row의 0의 수 Max값 index : {}'.format(np.max(row_zero_index)))
#     # print('col의 0의 수 Max값 index : {}'.format(np.max(col_zero_index)))

#     if(choice == 0):
#       choice_str = "행"
#     else:
#       choice_str = "열"
#     # print('삭제할 곳 선택 : {}'.format(choice_str))
#     if(choice == 0):
#       del_row_lst.append(row_zero_index[0])
#       stack_r1 = stack_r1.drop(row_zero_index[0], axis='columns')
#     else:
#       del_col_lst.append(col_zero_index[0])
#       stack_r1 = stack_r1.drop(columns=col_zero_index[0])
#     stack_r1= pd.DataFrame(np.array(stack_r1))
#     cnt += 1
# except:
#   print("")
#   # stack_r[2][2] = 0
#   # a = [0,1,2,3]
#   # del_row_index = []
#   # del_col_index = []
#   # for i in range(len(del_row_lst)):
#   #   del_row_index.append(a[del_row_lst[i]])
#   #   del a[del_row_lst[i]]
#   # a = [0,1,2,3]
#   # for i in range(len(del_col_lst)):
#   #   del_col_index.append(a[del_col_lst[i]])
#   #   del a[del_col_lst[i]]

    
#   # del_row_index, del_col_index    
#   # for i in range(len(del_row_index)):
#   #   if(len(del_col_index) >= 1):
#   #     for j in range(len(del_col_index)):
#   #       if(stack_r[del_row_index[i]][del_col_index[j]] == 0):
#   #         stack_r[del_row_index[i]][del_col_index[j]] += 1
#   # stack_r1 = stack_r.copy()

In [ ]:
# len(del_row_lst)

In [ ]:
# a = [0,1,2,3]
# del_row_index = []
# del_col_index = []
# for i in range(len(del_row_lst)):
#   del_row_index.append(a[del_row_lst[i]])
#   del a[del_row_lst[i]]
# a = [0,1,2,3]
# for i in range(len(del_col_lst)):
#   del_col_index.append(a[del_col_lst[i]])
#   del a[del_col_lst[i]]


# print(del_row_index, del_col_index)