<a href="https://colab.research.google.com/github/Junhyuck123/Production-control/blob/main/Final_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1737]:
import numpy as np
from scipy.optimize import linear_sum_assignment

c_m = np.array([[9,6,3,4],
                [5,8,12,10],
                [2,6,7,4],
                [4,11,13,7]])
row_ind, col_ind = linear_sum_assignment(c_m)
opt_ass = col_ind
tc = c_m[row_ind, col_ind].sum()


print(c_m)
print(opt_ass)
print(tc)

[[ 9  6  3  4]
 [ 5  8 12 10]
 [ 2  6  7  4]
 [ 4 11 13  7]]
[2 1 3 0]
19


In [1738]:
import numpy as np
import pandas as pd
!pip install pulp
import pulp

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# V1

In [1739]:
#n = int(input())
n =4

In [1740]:
job = []
resource = []
for i in range(n):
  job.append("J{}".format(i))
  resource.append("R{}".format(i))

for i in range(n):
  globals()["Col{}".format(i)] = []
  globals()["Low{}".format(i)] = []

In [1741]:
# c = np.random.randint(1, 15, size = (n, n))
# cost = pd.DataFrame(c, index = job, columns = resource)
# cost
cost = pd.DataFrame(c_m, index = job, columns = resource)
cost



R0  R1  R2  R3
J0   9   6   3   4
J1   5   8  12  10
J2   2   6   7   4
J3   4  11  13   7

In [1742]:
stack_c = pd.DataFrame()
for i in range(n):
  col = np.array(cost['R{}'.format(i)])
  col_min = min(col)
  col = col - col_min
  col = pd.DataFrame(col)
  stack_c[i] = col
stack_c

0  1   2  3
0  7  0   0  0
1  3  2   9  6
2  0  0   4  0
3  2  5  10  3

In [1743]:
stack_r = pd.DataFrame()
for i in range(n):
  row = stack_c.iloc[i][:]
  row_min = min(row)
  row = row - row_min
  row = pd.DataFrame(row)
  stack_r[i] = row
stack_r = stack_r.transpose()
stack_r

0  1  2  3
0  7  0  0  0
1  1  0  7  4
2  0  0  4  0
3  0  3  8  1

In [1744]:
count_col = 0
count_col_lst = []
for i in range(n):
  for j in range(n):
    if(stack_r.iloc[i][j] == 0):
      count_col += 1

  globals()["Zero_cnt_col{}".format(i)] = count_col
  count_col_lst.append(int(count_col))
  count_col = 0


count_row = 0
count_row_lst = []
for i in range(n):
  for j in range(n):
    if(stack_r.iloc[j][i] == 0):
      count_row += 1

  globals()["Zero_cnt_row{}".format(i)] = count_row
  count_row_lst.append(int(count_row))
  count_row = 0


print('row의 0의 수 : {}'.format(count_row_lst))
print('col의 0의 수 : {}'.format(count_col_lst))

row의 0의 수 : [2, 3, 1, 2]
col의 0의 수 : [3, 1, 3, 1]


In [1745]:
row_zero_index = [i for i, value in enumerate(count_row_lst) if value == np.max(count_row_lst)]
col_zero_index = [i for i, value in enumerate(count_col_lst) if value == np.max(count_col_lst)]

choice = []
choice.append(int(np.max(count_row_lst)))
choice.append(int(np.max(count_col_lst)))
choice = int(np.argmax(choice))
print('row의 0의 수 Max값 : {}'.format(np.max(count_row_lst)))
print('col의 0의 수 Max값 : {}'.format(np.max(count_col_lst)))
print('row의 0의 수 Max값 index : {}'.format(np.max(row_zero_index)))
print('col의 0의 수 Max값 index : {}'.format(np.max(col_zero_index)))

if(choice == 0):
  choice_str = "행"
else:
  choice_str = "열"
print('삭제할 곳 선택 : {}'.format(choice_str))

row의 0의 수 Max값 : 3
col의 0의 수 Max값 : 3
row의 0의 수 Max값 index : 1
col의 0의 수 Max값 index : 2
삭제할 곳 선택 : 행


In [1746]:
if(choice == 0):
  result_step1 = stack_r.drop(row_zero_index[0], axis='columns')
else:
  result_step1 = stack_r.drop(columns=col_zero_index[0])
result_step1= pd.DataFrame(np.array(result_step1))
result_step1

0  1  2
0  7  0  0
1  1  7  4
2  0  4  0
3  0  8  1

In [1747]:
count_col = 0
count_col_lst = []
for i in range(len(result_step1.index)):
  for j in range(len(result_step1.columns)):
    if(int(result_step1.iloc[i][j]) == 0):
      count_col += 1
  globals()["Zero_cnt_col{}".format(i)] = count_col
  count_col_lst.append(int(count_col))
  count_col = 0

count_row = 0
count_row_lst = []
for i in range(len(result_step1.columns)):
  for j in range(len(result_step1.index)):
    if(int(result_step1.iloc[j][i]) == 0):
      count_row += 1

  globals()["Zero_cnt_row{}".format(i)] = count_row
  count_row_lst.append(int(count_row))
  count_row = 0


In [1748]:
row_zero_index = [i for i, value in enumerate(count_row_lst) if value == np.max(count_row_lst)]
col_zero_index = [i for i, value in enumerate(count_col_lst) if value == np.max(count_col_lst)]

choice = []
choice.append(int(np.max(count_row_lst)))
choice.append(int(np.max(count_col_lst)))
choice = int(np.argmax(choice))
np.max(count_row_lst),np.max(count_col_lst), choice

(2, 2, 0)

In [1749]:
count_row_lst, count_col_lst 

([2, 1, 2], [2, 0, 2, 1])

In [1750]:
choice

0

In [1751]:
if(choice == 0):
  result_step2 = result_step1.drop(row_zero_index[0], axis='columns')
else:
  result_step2 = result_step1.drop(columns=col_zero_index[0])


In [1752]:
result_step2

1  2
0  0  0
1  7  4
2  4  0
3  8  1

In [1753]:
result_step2= pd.DataFrame(np.array(result_step2))

In [1754]:
result_step2

0  1
0  0  0
1  7  4
2  4  0
3  8  1

In [1755]:
count_col = 0
count_col_lst = []
for i in range(len(result_step2.index)):
  for j in range(len(result_step2.columns)):
    if(int(result_step2.iloc[i][j]) == 0):
      count_col += 1
  globals()["Zero_cnt_col{}".format(i)] = count_col
  count_col_lst.append(int(count_col))
  count_col = 0

count_row = 0
count_row_lst = []
for i in range(len(result_step2.columns)):
  for j in range(len(result_step2.index)):
    if(int(result_step2.iloc[j][i]) == 0):
      count_row += 1

  globals()["Zero_cnt_row{}".format(i)] = count_row
  count_row_lst.append(int(count_row))
  count_row = 0


In [1756]:
row_zero_index = [i for i, value in enumerate(count_row_lst) if value == np.max(count_row_lst)]
col_zero_index = [i for i, value in enumerate(count_col_lst) if value == np.max(count_col_lst)]

choice = []
choice.append(int(np.max(count_row_lst)))
choice.append(int(np.max(count_col_lst)))
choice = int(np.argmax(choice))
np.max(count_row_lst),np.max(count_col_lst), choice

(2, 2, 0)

In [1757]:
count_row_lst, count_col_lst 

([1, 2], [2, 0, 1, 0])

In [1758]:
choice

0

In [1759]:
if(choice == 0):
  result_step3 = result_step2.drop(row_zero_index[0], axis='columns')
else:
  result_step3 = result_step2.drop(columns=col_zero_index[0])


In [1760]:
result_step3

0
0  0
1  7
2  4
3  8

## 3

In [1761]:
count_col = 0
count_col_lst = []
for i in range(len(result_step3.index)):
  for j in range(len(result_step3.columns)):
    if(int(result_step3.iloc[i][j]) == 0):
      count_col += 1
  globals()["Zero_cnt_col{}".format(i)] = count_col
  count_col_lst.append(int(count_col))
  count_col = 0

count_row = 0
count_row_lst = []
for i in range(len(result_step3.columns)):
  for j in range(len(result_step3.index)):
    if(int(result_step3.iloc[j][i]) == 0):
      count_row += 1

  globals()["Zero_cnt_row{}".format(i)] = count_row
  count_row_lst.append(int(count_row))
  count_row = 0


In [1762]:
row_zero_index = [i for i, value in enumerate(count_row_lst) if value == np.max(count_row_lst)]
col_zero_index = [i for i, value in enumerate(count_col_lst) if value == np.max(count_col_lst)]

choice = []
choice.append(int(np.max(count_row_lst)))
choice.append(int(np.max(count_col_lst)))
choice = int(np.argmax(choice))
np.max(count_row_lst),np.max(count_col_lst), choice

(1, 1, 0)

In [1763]:
count_row_lst, count_col_lst 

([1], [1, 0, 0, 0])

In [1764]:
choice

0

In [1765]:
if(choice == 0):
  result_step4 = result_step3.drop(row_zero_index[0], axis='columns')
else:
  result_step4 = result_step3.drop(columns=col_zero_index[0])


In [1766]:
result_step4

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

# V2

In [1767]:
stack_r1 = pd.DataFrame()
stack_r1 = stack_r.copy()
del_row_lst = []
del_col_lst = []
row_cnt = 0
col_cnt = 0
cnt = 0

In [1768]:
try:
  # for i in range(n):
  #   for j in range(n):
  #     if(stack_r1[i][j] == 0):
  #       cnt +=1
  #while(len(del_row_lst)+len(del_col_lst) < n):
  for d in range(n):
    count_col = 0
    count_col_lst = []
    for i in range(len(stack_r1.index)):
      for j in range(len(stack_r1.columns)):
        if(stack_r1.iloc[i][j] == 0):
          count_col += 1

      # globals()["Zero_cnt_col{}".format(i)] = count_col
      count_col_lst.append(int(count_col))
      count_col = 0


    count_row = 0
    count_row_lst = []
    for i in range(len(stack_r1.columns)):
      for j in range(len(stack_r1.index)):
        if(stack_r1.iloc[j][i] == 0):
          count_row += 1

      # globals()["Zero_cnt_row{}".format(i)] = count_row
      count_row_lst.append(int(count_row))
      count_row = 0


    # print('row의 0의 수 : {}'.format(count_row_lst))
    # print('col의 0의 수 : {}'.format(count_col_lst))
    row_zero_index = [i for i, value in enumerate(count_row_lst) if value == np.max(count_row_lst)]
    col_zero_index = [i for i, value in enumerate(count_col_lst) if value == np.max(count_col_lst)]

    choice = []
    choice.append(int(np.max(count_row_lst)))
    choice.append(int(np.max(count_col_lst)))
    choice = int(np.argmax(choice))
    # print('row의 0의 수 Max값 : {}'.format(np.max(count_row_lst)))
    # print('col의 0의 수 Max값 : {}'.format(np.max(count_col_lst)))
    # print('row의 0의 수 Max값 index : {}'.format(np.max(row_zero_index)))
    # print('col의 0의 수 Max값 index : {}'.format(np.max(col_zero_index)))

    if(choice == 0):
      choice_str = "행"
    else:
      choice_str = "열"
    # print('삭제할 곳 선택 : {}'.format(choice_str))
    if(choice == 0):
      del_row_lst.append(row_zero_index[0])
      stack_r1 = stack_r1.drop(row_zero_index[0], axis='columns')
    else:
      del_col_lst.append(col_zero_index[0])
      stack_r1 = stack_r1.drop(columns=col_zero_index[0])
    stack_r1= pd.DataFrame(np.array(stack_r1))
    cnt += 1
except:
  print("")
  # stack_r[2][2] = 0
  # a = [0,1,2,3]
  # del_row_index = []
  # del_col_index = []
  # for i in range(len(del_row_lst)):
  #   del_row_index.append(a[del_row_lst[i]])
  #   del a[del_row_lst[i]]
  # a = [0,1,2,3]
  # for i in range(len(del_col_lst)):
  #   del_col_index.append(a[del_col_lst[i]])
  #   del a[del_col_lst[i]]

    
  # del_row_index, del_col_index    
  # for i in range(len(del_row_index)):
  #   if(len(del_col_index) >= 1):
  #     for j in range(len(del_col_index)):
  #       if(stack_r[del_row_index[i]][del_col_index[j]] == 0):
  #         stack_r[del_row_index[i]][del_col_index[j]] += 1
  # stack_r1 = stack_r.copy()

In [1769]:
stack_r1

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [1770]:
cnt

4

In [1771]:
del_row_lst, del_col_lst

([1, 0, 1, 0], [])

In [1778]:
a = [0,1,2,3]
del_row_index = []
del_col_index = []
for i in range(len(del_row_lst)):
  del_row_index.append(a[del_row_lst[i]])
  del a[del_row_lst[i]]
a = [0,1,2,3]
for i in range(len(del_col_lst)):
  del_col_index.append(a[del_col_lst[i]])
  del a[del_col_lst[i]]


print(del_row_index, del_col_index)

c = np.random.randint(1, 2, size = (n, n))

for i in range(len(del_row_index)):
  c[del_row_index[i]] = 0
for j in range(len(del_col_index)):
  c.loc[del_col_index[j]] = 0

[1, 0, 3, 2] []


In [1779]:
plus = pd.DataFrame(c)

In [1780]:
stack_r1 = stack_r + plus

In [1781]:
try:
  # for i in range(n):
  #   for j in range(n):
  #     if(stack_r1[i][j] == 0):
  #       cnt +=1
  #while(len(del_row_lst)+len(del_col_lst) < n):
  for d in range(n):
    count_col = 0
    count_col_lst = []
    for i in range(len(stack_r1.index)):
      for j in range(len(stack_r1.columns)):
        if(stack_r1.iloc[i][j] == 0):
          count_col += 1

      # globals()["Zero_cnt_col{}".format(i)] = count_col
      count_col_lst.append(int(count_col))
      count_col = 0


    count_row = 0
    count_row_lst = []
    for i in range(len(stack_r1.columns)):
      for j in range(len(stack_r1.index)):
        if(stack_r1.iloc[j][i] == 0):
          count_row += 1

      # globals()["Zero_cnt_row{}".format(i)] = count_row
      count_row_lst.append(int(count_row))
      count_row = 0


    # print('row의 0의 수 : {}'.format(count_row_lst))
    # print('col의 0의 수 : {}'.format(count_col_lst))
    row_zero_index = [i for i, value in enumerate(count_row_lst) if value == np.max(count_row_lst)]
    col_zero_index = [i for i, value in enumerate(count_col_lst) if value == np.max(count_col_lst)]

    choice = []
    choice.append(int(np.max(count_row_lst)))
    choice.append(int(np.max(count_col_lst)))
    choice = int(np.argmax(choice))
    # print('row의 0의 수 Max값 : {}'.format(np.max(count_row_lst)))
    # print('col의 0의 수 Max값 : {}'.format(np.max(count_col_lst)))
    # print('row의 0의 수 Max값 index : {}'.format(np.max(row_zero_index)))
    # print('col의 0의 수 Max값 index : {}'.format(np.max(col_zero_index)))

    if(choice == 0):
      choice_str = "행"
    else:
      choice_str = "열"
    # print('삭제할 곳 선택 : {}'.format(choice_str))
    if(choice == 0):
      del_row_lst.append(row_zero_index[0])
      stack_r1 = stack_r1.drop(row_zero_index[0], axis='columns')
    else:
      del_col_lst.append(col_zero_index[0])
      stack_r1 = stack_r1.drop(columns=col_zero_index[0])
    stack_r1= pd.DataFrame(np.array(stack_r1))
    cnt += 1
except:
  print("")
  # stack_r[2][2] = 0
  # a = [0,1,2,3]
  # del_row_index = []
  # del_col_index = []
  # for i in range(len(del_row_lst)):
  #   del_row_index.append(a[del_row_lst[i]])
  #   del a[del_row_lst[i]]
  # a = [0,1,2,3]
  # for i in range(len(del_col_lst)):
  #   del_col_index.append(a[del_col_lst[i]])
  #   del a[del_col_lst[i]]

    
  # del_row_index, del_col_index    
  # for i in range(len(del_row_index)):
  #   if(len(del_col_index) >= 1):
  #     for j in range(len(del_col_index)):
  #       if(stack_r[del_row_index[i]][del_col_index[j]] == 0):
  #         stack_r[del_row_index[i]][del_col_index[j]] += 1
  # stack_r1 = stack_r.copy()

In [1783]:
len(del_row_lst)

8

In [1782]:
a = [0,1,2,3]
del_row_index = []
del_col_index = []
for i in range(len(del_row_lst)):
  del_row_index.append(a[del_row_lst[i]])
  del a[del_row_lst[i]]
a = [0,1,2,3]
for i in range(len(del_col_lst)):
  del_col_index.append(a[del_col_lst[i]])
  del a[del_col_lst[i]]


print(del_row_index, del_col_index)

IndexError: ignored