<a href="https://colab.research.google.com/github/Junhyuck123/Production-control/blob/main/Final_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3225]:
import numpy as np
import pandas as pd
from scipy.optimize import linear_sum_assignment

c_m = np.array([[9,6,3,4],
                [5,8,12,10],
                [2,6,7,4],
                [4,11,13,7]])
row_ind, col_ind = linear_sum_assignment(c_m)
opt_ass = col_ind
tc = c_m[row_ind, col_ind].sum()


print(c_m)
print(opt_ass)
print(tc)

[[ 9  6  3  4]
 [ 5  8 12 10]
 [ 2  6  7  4]
 [ 4 11 13  7]]
[2 1 3 0]
19


In [3149]:
#n = int(input())
n =4

In [3226]:
# c = np.random.randint(1, 15, size = (n, n))
# cost = pd.DataFrame(c)
# cost
cost = pd.DataFrame(c_m)
cost



0   1   2   3
0  9   6   3   4
1  5   8  12  10
2  2   6   7   4
3  4  11  13   7

In [3152]:
stack_c = pd.DataFrame()
for i in range(n):
  col = np.array(cost['R{}'.format(i)])
  col_min = min(col)
  col = col - col_min
  col = pd.DataFrame(col)
  stack_c[i] = col
stack_c

0  1   2  3
0  7  0   0  0
1  3  2   9  6
2  0  0   4  0
3  2  5  10  3

In [3153]:
pre_Data = pd.DataFrame()
for i in range(n):
  row = stack_c.iloc[i][:]
  row_min = min(row)
  row = row - row_min
  row = pd.DataFrame(row)
  pre_Data[i] = row
pre_Data = pre_Data.transpose()
pre_Data

0  1  2  3
0  7  0  0  0
1  1  0  7  4
2  0  0  4  0
3  0  3  8  1

In [3154]:
count_col = 0
count_col_lst = []
for i in range(n):
  for j in range(n):
    if(pre_Data.iloc[i][j] == 0):
      count_col += 1

  globals()["Zero_cnt_col{}".format(i)] = count_col
  count_col_lst.append(int(count_col))
  count_col = 0


count_row = 0
count_row_lst = []
for i in range(n):
  for j in range(n):
    if(pre_Data.iloc[j][i] == 0):
      count_row += 1

  globals()["Zero_cnt_row{}".format(i)] = count_row
  count_row_lst.append(int(count_row))
  count_row = 0


print('row의 0의 수 : {}'.format(count_row_lst))
print('col의 0의 수 : {}'.format(count_col_lst))

row의 0의 수 : [2, 3, 1, 2]
col의 0의 수 : [3, 1, 3, 1]


In [3155]:
row_zero_index = [i for i, value in enumerate(count_row_lst) if value == np.max(count_row_lst)]
col_zero_index = [i for i, value in enumerate(count_col_lst) if value == np.max(count_col_lst)]

choice = []
choice.append(int(np.max(count_row_lst)))
choice.append(int(np.max(count_col_lst)))
choice = int(np.argmax(choice))
print('row의 0의 수 Max값 : {}'.format(np.max(count_row_lst)))
print('col의 0의 수 Max값 : {}'.format(np.max(count_col_lst)))
print('row의 0의 수 Max값 index : {}'.format(np.max(row_zero_index)))
print('col의 0의 수 Max값 index : {}'.format(np.max(col_zero_index)))

if(choice == 0):
  choice_str = "행"
else:
  choice_str = "열"
print('삭제할 곳 선택 : {}'.format(choice_str))

row의 0의 수 Max값 : 3
col의 0의 수 Max값 : 3
row의 0의 수 Max값 index : 1
col의 0의 수 Max값 index : 2
삭제할 곳 선택 : 행


In [3156]:
if(choice == 0):
  result_step1 = pre_Data.drop(row_zero_index[0], axis='columns')
else:
  result_step1 = pre_Data.drop(columns=col_zero_index[0])
result_step1= pd.DataFrame(np.array(result_step1))
result_step1

0  1  2
0  7  0  0
1  1  7  4
2  0  4  0
3  0  8  1

In [3157]:
count_col = 0
count_col_lst = []
for i in range(len(result_step1.index)):
  for j in range(len(result_step1.columns)):
    if(int(result_step1.iloc[i][j]) == 0):
      count_col += 1
  globals()["Zero_cnt_col{}".format(i)] = count_col
  count_col_lst.append(int(count_col))
  count_col = 0

count_row = 0
count_row_lst = []
for i in range(len(result_step1.columns)):
  for j in range(len(result_step1.index)):
    if(int(result_step1.iloc[j][i]) == 0):
      count_row += 1

  globals()["Zero_cnt_row{}".format(i)] = count_row
  count_row_lst.append(int(count_row))
  count_row = 0


In [3158]:
row_zero_index = [i for i, value in enumerate(count_row_lst) if value == np.max(count_row_lst)]
col_zero_index = [i for i, value in enumerate(count_col_lst) if value == np.max(count_col_lst)]

choice = []
choice.append(int(np.max(count_row_lst)))
choice.append(int(np.max(count_col_lst)))
choice = int(np.argmax(choice))
np.max(count_row_lst),np.max(count_col_lst), choice

(2, 2, 0)

In [3159]:
count_row_lst, count_col_lst 

([2, 1, 2], [2, 0, 2, 1])

In [3160]:
choice

0

In [3161]:
if(choice == 0):
  result_step2 = result_step1.drop(row_zero_index[0], axis='columns')
else:
  result_step2 = result_step1.drop(columns=col_zero_index[0])


In [3162]:
result_step2

1  2
0  0  0
1  7  4
2  4  0
3  8  1

In [3163]:
result_step2= pd.DataFrame(np.array(result_step2))

In [3164]:
result_step2

0  1
0  0  0
1  7  4
2  4  0
3  8  1

In [3165]:
count_col = 0
count_col_lst = []
for i in range(len(result_step2.index)):
  for j in range(len(result_step2.columns)):
    if(int(result_step2.iloc[i][j]) == 0):
      count_col += 1
  globals()["Zero_cnt_col{}".format(i)] = count_col
  count_col_lst.append(int(count_col))
  count_col = 0

count_row = 0
count_row_lst = []
for i in range(len(result_step2.columns)):
  for j in range(len(result_step2.index)):
    if(int(result_step2.iloc[j][i]) == 0):
      count_row += 1

  globals()["Zero_cnt_row{}".format(i)] = count_row
  count_row_lst.append(int(count_row))
  count_row = 0


In [3166]:
row_zero_index = [i for i, value in enumerate(count_row_lst) if value == np.max(count_row_lst)]
col_zero_index = [i for i, value in enumerate(count_col_lst) if value == np.max(count_col_lst)]

choice = []
choice.append(int(np.max(count_row_lst)))
choice.append(int(np.max(count_col_lst)))
choice = int(np.argmax(choice))
np.max(count_row_lst),np.max(count_col_lst), choice

(2, 2, 0)

In [3167]:
count_row_lst, count_col_lst 

([1, 2], [2, 0, 1, 0])

In [3168]:
choice

0

In [3169]:
if(choice == 0):
  result_step3 = result_step2.drop(row_zero_index[0], axis='columns')
else:
  result_step3 = result_step2.drop(columns=col_zero_index[0])


In [3170]:
result_step3

0
0  0
1  7
2  4
3  8

## 3

In [3171]:
count_col = 0
count_col_lst = []
for i in range(len(result_step3.index)):
  for j in range(len(result_step3.columns)):
    if(int(result_step3.iloc[i][j]) == 0):
      count_col += 1
  globals()["Zero_cnt_col{}".format(i)] = count_col
  count_col_lst.append(int(count_col))
  count_col = 0

count_row = 0
count_row_lst = []
for i in range(len(result_step3.columns)):
  for j in range(len(result_step3.index)):
    if(int(result_step3.iloc[j][i]) == 0):
      count_row += 1

  globals()["Zero_cnt_row{}".format(i)] = count_row
  count_row_lst.append(int(count_row))
  count_row = 0


In [3172]:
row_zero_index = [i for i, value in enumerate(count_row_lst) if value == np.max(count_row_lst)]
col_zero_index = [i for i, value in enumerate(count_col_lst) if value == np.max(count_col_lst)]

choice = []
choice.append(int(np.max(count_row_lst)))
choice.append(int(np.max(count_col_lst)))
choice = int(np.argmax(choice))
np.max(count_row_lst),np.max(count_col_lst), choice

(1, 1, 0)

In [3173]:
count_row_lst, count_col_lst 

([1], [1, 0, 0, 0])

In [3174]:
choice

0

In [3175]:
if(choice == 0):
  result_step4 = result_step3.drop(row_zero_index[0], axis='columns')
else:
  result_step4 = result_step3.drop(columns=col_zero_index[0])


In [3176]:
result_step4

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

# V2

In [3177]:
pre_Data1 = pd.DataFrame()
pre_Data1 = pre_Data.copy()
del_row_lst = [] # 삭제한 행 목록
del_col_lst = [] # 삭제한 열 목록
row_cnt = 0 # 행에서 0의 갯수
col_cnt = 0 # 열에서 0의 갯수
cnt = 0 # For 루프 시행 횟수

In [3178]:
pre_Data1

0  1  2  3
0  7  0  0  0
1  1  0  7  4
2  0  0  4  0
3  0  3  8  1

In [3179]:
pre_Data1.iloc[1][0] #행,열

1

In [3180]:
len(pre_Data1.columns)

4

In [3181]:
# try: # n번의 시행중 시행횟수가 일치하지 않을 시 오류취급 for 루프 중단
for d in range(n): # n matrix의 경우 n번 시행
  print("---------------{}번째 시행---------------".format(d))

  #ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
  count_col = 0
  count_col_lst = []
  for i in range(len(pre_Data1.columns)):
    for j in range(len(pre_Data1.index)):
      if(pre_Data1.iloc[j][i] == 0):
        count_col += 1

    count_col_lst.append(int(count_col))
    print('col의 0의 수 : {}'.format(count_col_lst))
    count_col = 0
  #ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
  count_row = 0 # col의 index별 0의갯수 초기화
  count_row_lst = [] # 열 별 0의 갯수 저장
  for i in range(len(pre_Data1.index)):
    for j in range(len(pre_Data1.columns)): # 열과 행의 갯수 만큼 for 문 실행 (삭제하며 찾기 때문에 n이 아닌 len루프)
      if(pre_Data1.iloc[i][j] == 0): 
        count_row += 1

    count_row_lst.append(int(count_row))
    print('row의 0의 수 : {}'.format(count_row_lst))
    count_row = 0


  #ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

  
  # Zero 개수의 최대값 index를 저장하는 리스트
  col_zero_index = [i for i, value in enumerate(count_col_lst) if value == np.max(count_col_lst)]
  row_zero_index = [i for i, value in enumerate(count_row_lst) if value == np.max(count_row_lst)]

  #ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
  # 행을 삭제할지 열을 삭제할지 결정
  choice = []
  choice.append(int(np.max(count_col_lst)))
  choice.append(int(np.max(count_row_lst)))
  print(choice)
  choice = int(np.argmax(choice)) # 같은 숫자일 경우 행을 삭제
  print('col의 0의 수 Max값 : {}'.format(np.max(count_col_lst)))
  print('row의 0의 수 Max값 : {}'.format(np.max(count_row_lst)))
  print('col의 0의 수 Max값 index : {}'.format(np.max(col_zero_index)))
  print('row의 0의 수 Max값 index : {}'.format(np.max(row_zero_index)))
  
  print(pre_Data1)


  if(choice == 0): #어떤 행 Or 열을 커버하는지 Print하기 위한 
    choice_str = "열"
  else:
    choice_str = "행"
  print('커버 할 행 또는 열 선택 : {0}'.format(choice_str))  # 단순 출력

  if(choice == 0): # 행을 선택한 경우 삭제
    del_col_lst.append(col_zero_index[0])
    pre_Data1 = pre_Data1.drop(columns=col_zero_index[0])
  else: #열을 선택한 경우
    del_row_lst.append(row_zero_index[0])
    pre_Data1 = pre_Data1.drop(row_zero_index[0], axis='columns')

  pre_Data1= pd.DataFrame(np.array(pre_Data1)) #DataFrame형태로 재변환 (1열을 삭제할 경우 index가 0 2 3 으로 처리 --> for문에서 오류발생)
  cnt += 1





if(cnt != 4): # 커버하는 선의 수가 4개 이하인 경우 아래 셀 추가 실행
  print("아래 항목을 실행하세요")
# except:
#   print("Error")

---------------0번째 시행---------------
col의 0의 수 : [2]
col의 0의 수 : [2, 3]
col의 0의 수 : [2, 3, 1]
col의 0의 수 : [2, 3, 1, 2]
row의 0의 수 : [3]
row의 0의 수 : [3, 1]
row의 0의 수 : [3, 1, 3]
row의 0의 수 : [3, 1, 3, 1]
[3, 3]
col의 0의 수 Max값 : 3
row의 0의 수 Max값 : 3
col의 0의 수 Max값 index : 1
row의 0의 수 Max값 index : 2
   0  1  2  3
0  7  0  0  0
1  1  0  7  4
2  0  0  4  0
3  0  3  8  1
커버 할 행 또는 열 선택 : 열
---------------1번째 시행---------------
col의 0의 수 : [2]
col의 0의 수 : [2, 1]
col의 0의 수 : [2, 1, 2]
row의 0의 수 : [2]
row의 0의 수 : [2, 0]
row의 0의 수 : [2, 0, 2]
row의 0의 수 : [2, 0, 2, 1]
[2, 2]
col의 0의 수 Max값 : 2
row의 0의 수 Max값 : 2
col의 0의 수 Max값 index : 2
row의 0의 수 Max값 index : 2
   0  1  2
0  7  0  0
1  1  7  4
2  0  4  0
3  0  8  1
커버 할 행 또는 열 선택 : 열
---------------2번째 시행---------------
col의 0의 수 : [1]
col의 0의 수 : [1, 2]
row의 0의 수 : [2]
row의 0의 수 : [2, 0]
row의 0의 수 : [2, 0, 1]
row의 0의 수 : [2, 0, 1, 0]
[2, 2]
col의 0의 수 Max값 : 2
row의 0의 수 Max값 : 2
col의 0의 수 Max값 index : 1
row의 0의 수 Max값 index : 0
   0  1
0  0  0
1  7 

### Cnt != 4

In [3182]:
Data_Array = np.array(pre_Data)

In [3183]:
# ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
 
# 커버한 열 또는 행의 index를 저장하는 문장
num = list(range(n))
del_row_index = []
del_col_index = []

for i in range(len(del_col_lst)): 
  del_col_index.append(num[del_col_lst[i]])
  del num[del_col_lst[i]]

num = list(range(n))

for i in range(len(del_row_lst)):
  del_row_index.append(num[del_row_lst[i]])
  del num[del_row_lst[i]]
# ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

# ??

# for i in range(len(del_row_index)):
#   if(len(del_col_index) >= 1):
#     for j in range(len(del_col_index)):
#       if(pre_Data[del_row_index[i]][del_col_index[j]] == 0):
#         pre_Data[del_row_index[i]][del_col_index[j]] += 1
# pre_Data1 = pre_Data.copy()

In [3184]:
del_row_index, del_col_index


([], [1, 0, 3, 2])

In [3185]:
pre_Data

0  1  2  3
0  7  0  0  0
1  1  0  7  4
2  0  0  4  0
3  0  3  8  1

In [3186]:
Data_Array

array([[7, 0, 0, 0],
       [1, 0, 7, 4],
       [0, 0, 4, 0],
       [0, 3, 8, 1]])

### 결과 뽑기칸


In [3187]:
if(cnt != 3): #Test용
  num = list(range(n))
  plus_row = list(set(num)-set(del_row_index))


  Cross_matrix = np.random.randint(0, 1, size = (n, n))
  double_Cross_matrix = np.random.randint(0, 1, size = (n, n))
  Not_cov_matrix = np.random.randint(1, 2, size = (n, n))
  for i in range(len(del_row_index)):
    Not_cov_matrix[del_row_index[i]] = 0
    for j in range(len(del_col_index)):
      Cross_matrix[del_row_index[i]][del_col_index[j]] = 1
      for k in range(len(plus_row)):
        Not_cov_matrix[plus_row[k]][del_col_index[j]] = 0
        double_Cross_matrix[plus_row[k]][del_col_index[j]] = 1

In [3188]:
Not_cov_matrix

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [3189]:
Not_cov_matrix_val = np.multiply(Data_Array, Not_cov_matrix)
min_val = np.min(Not_cov_matrix_val[Not_cov_matrix_val!=0])


pre_Data2 = pd.DataFrame(Data_Array - min_val * Not_cov_matrix + min_val*Cross_matrix + min_val * double_Cross_matrix)

In [3190]:
pre_Data

0  1  2  3
0  7  0  0  0
1  1  0  7  4
2  0  0  4  0
3  0  3  8  1

In [3191]:
Data_Array

array([[7, 0, 0, 0],
       [1, 0, 7, 4],
       [0, 0, 4, 0],
       [0, 3, 8, 1]])

In [3192]:
count_col = 0
count_col_lst = []
for i in range(len(pre_Data.columns)):
  for j in range(len(pre_Data.index)):
    if(pre_Data.iloc[j][i] == 0):
      count_col += 1

  count_col_lst.append(int(count_col))
  print('col의 0의 수 : {}'.format(count_col_lst))
  count_col = 0
#ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
count_row = 0 # col의 index별 0의갯수 초기화
count_row_lst = [] # 열 별 0의 갯수 저장
for i in range(len(pre_Data.index)):
  for j in range(len(pre_Data.columns)): # 열과 행의 갯수 만큼 for 문 실행 (삭제하며 찾기 때문에 n이 아닌 len루프)
    if(pre_Data.iloc[i][j] == 0): 
      count_row += 1

  count_row_lst.append(int(count_row))
  print('row의 0의 수 : {}'.format(count_row_lst))
  count_row = 0


col의 0의 수 : [2]
col의 0의 수 : [2, 3]
col의 0의 수 : [2, 3, 1]
col의 0의 수 : [2, 3, 1, 2]
row의 0의 수 : [3]
row의 0의 수 : [3, 1]
row의 0의 수 : [3, 1, 3]
row의 0의 수 : [3, 1, 3, 1]


In [3193]:
count_col_lst , count_row_lst

([2, 3, 1, 2], [3, 1, 3, 1])

In [3194]:
np.argmin(count_col_lst)

2

In [3195]:
result = np.zeros([n,n])
result[np.argmin(count_col_lst),np.argmin(Data_Array[np.argmin(count_col_lst),:])] = 1


In [3196]:
result

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3197]:
col_zero_index = [i for i, value in enumerate(count_col_lst) if value == np.min(count_col_lst)]

# 결과 뽑기 시각화

In [3199]:
DataArray = np.array(pre_Data)
col = []
for i in range(n):
  count = 0
  for j in range(n):
    if(DataArray[j,i] == 0):
      count +=1
  col.append(count)

row = []
for i in range(n):
  count = 0
  for j in range(n):
    if(DataArray[i,j] == 0):
      count +=1
  row.append(count)

In [3200]:
DataArray1 = DataArray
result = np.zeros([n,n])
DataArray1

In [3202]:
if(np.min(col) <= np.min(row)):
  result[np.argmin(DataArray1[:,np.argmin(col)]),np.argmin(col)] = 1  # np.argmin(col) ==> 0~3열중 2열, np.argmin(DataArray1[:,np.argmin(col)])==> 2열중 0이 가장 작은 0행
  # ==> 커버한 열과 행을 1로 대체 (0을 삭제)
  DataArray1[np.argmin(DataArray1[:,np.argmin(col)]),:] = 1
  DataArray1[:,np.argmin(col)] = 1
else:
  result[np.argmin(row), np.argmin(DataArray1[np.argmin(row),:])] = 1 # np.argmin(row) # 0~3행 중 1행, np.argmin(DataArray1[np.argmin(row),:]) # 1행중 1열

  DataArray1[np.argmin(row),:] = 1 
  DataArray1[:,np.argmin(DataArray1[np.argmin(row),:])] =1

In [3203]:
result

array([[0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3204]:
col = []
for i in range(n):
  count = 0
  for j in range(n):
    if(DataArray1[j,i] == 0):
      count +=1
  col.append(count)
  if(col[np.argmin(col)] == 0):
    col[np.argmin(col)] = 100
row = []
for i in range(n):
  count = 0
  for j in range(n):
    if(DataArray1[i,j] == 0):
      count +=1
  row.append(count)
  if(row[np.argmin(row)] == 0):
    row[np.argmin(row)] = 100

In [3205]:
if(np.min(col) <= np.min(row)):
  result[np.argmin(DataArray1[:,np.argmin(col)]),np.argmin(col)] = 1  # np.argmin(col) ==> 0~3열중 2열, np.argmin(DataArray1[:,np.argmin(col)])==> 2열중 0이 가장 작은 0행
  # ==> 커버한 열과 행을 1로 대체 (0을 삭제)
  DataArray1[np.argmin(DataArray1[:,np.argmin(col)]),:] = 1
  DataArray1[:,np.argmin(col)] = 1
else:
  result[np.argmin(row), np.argmin(DataArray1[np.argmin(row),:])] = 1 # np.argmin(row) # 0~3행 중 1행, np.argmin(DataArray1[np.argmin(row),:]) # 1행중 1열

  DataArray1[np.argmin(row),:] = 1 
  DataArray1[:,np.argmin(DataArray1[np.argmin(row),:])] =1

In [3206]:
result

array([[0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [3207]:
col = []
for i in range(n):
  count = 0
  for j in range(n):
    if(DataArray1[j,i] == 0):
      count +=1
  col.append(count)
  if(col[np.argmin(col)] == 0):
    col[np.argmin(col)] = 100
row = []
for i in range(n):
  count = 0
  for j in range(n):
    if(DataArray1[i,j] == 0):
      count +=1
  row.append(count)
  if(row[np.argmin(row)] == 0):
    row[np.argmin(row)] = 100

In [3208]:
if(np.min(col) <= np.min(row)):
  result[np.argmin(DataArray1[:,np.argmin(col)]),np.argmin(col)] = 1  # np.argmin(col) ==> 0~3열중 2열, np.argmin(DataArray1[:,np.argmin(col)])==> 2열중 0이 가장 작은 0행
  # ==> 커버한 열과 행을 1로 대체 (0을 삭제)
  DataArray1[np.argmin(DataArray1[:,np.argmin(col)]),:] = 1
  DataArray1[:,np.argmin(col)] = 1
else:
  result[np.argmin(row), np.argmin(DataArray1[np.argmin(row),:])] = 1 # np.argmin(row) # 0~3행 중 1행, np.argmin(DataArray1[np.argmin(row),:]) # 1행중 1열

  DataArray1[np.argmin(row),:] = 1 
  DataArray1[:,np.argmin(DataArray1[np.argmin(row),:])] =1

In [3209]:
result

array([[0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.]])

In [3210]:
col = []
for i in range(n):
  count = 0
  for j in range(n):
    if(DataArray1[j,i] == 0):
      count +=1
  col.append(count)
  if(col[np.argmin(col)] == 0):
    col[np.argmin(col)] = 100
row = []
for i in range(n):
  count = 0
  for j in range(n):
    if(DataArray1[i,j] == 0):
      count +=1
  row.append(count)
  if(row[np.argmin(row)] == 0):
    row[np.argmin(row)] = 100

In [3211]:
if(np.min(col) <= np.min(row)):
  result[np.argmin(DataArray1[:,np.argmin(col)]),np.argmin(col)] = 1  # np.argmin(col) ==> 0~3열중 2열, np.argmin(DataArray1[:,np.argmin(col)])==> 2열중 0이 가장 작은 0행
  # ==> 커버한 열과 행을 1로 대체 (0을 삭제)
  DataArray1[np.argmin(DataArray1[:,np.argmin(col)]),:] = 1
  DataArray1[:,np.argmin(col)] = 1
else:
  result[np.argmin(row), np.argmin(DataArray1[np.argmin(row),:])] = 1 # np.argmin(row) # 0~3행 중 1행, np.argmin(DataArray1[np.argmin(row),:]) # 1행중 1열

  DataArray1[np.argmin(row),:] = 1 
  DataArray1[:,np.argmin(DataArray1[np.argmin(row),:])] =1

In [3212]:
result

array([[0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.]])

In [3224]:
Total_Cost = np.multiply(c_m, result).sum()
Total_Cost

19.0

# 결과 한번에 뽑기

In [ ]:
DataArray = np.array(pre_Data)
col = []
for i in range(n):
  count = 0
  for j in range(n):
    if(DataArray[j,i] == 0):
      count +=1
  col.append(count)

row = []
for i in range(n):
  count = 0
  for j in range(n):
    if(DataArray[i,j] == 0):
      count +=1
  row.append(count)

In [ ]:
DataArray1 = DataArray
result = np.zeros([n,n])
DataArray1

In [ ]:
if(np.min(col) <= np.min(row)):
  result[np.argmin(DataArray1[:,np.argmin(col)]),np.argmin(col)] = 1  # np.argmin(col) ==> 0~3열중 2열, np.argmin(DataArray1[:,np.argmin(col)])==> 2열중 0이 가장 작은 0행
  # ==> 커버한 열과 행을 1로 대체 (0을 삭제)
  DataArray1[np.argmin(DataArray1[:,np.argmin(col)]),:] = 1
  DataArray1[:,np.argmin(col)] = 1
else:
  result[np.argmin(row), np.argmin(DataArray1[np.argmin(row),:])] = 1 # np.argmin(row) # 0~3행 중 1행, np.argmin(DataArray1[np.argmin(row),:]) # 1행중 1열

  DataArray1[np.argmin(row),:] = 1 
  DataArray1[:,np.argmin(DataArray1[np.argmin(row),:])] =1

In [3212]:
for k in range(n-1):
  col = []
  for i in range(n):
    count = 0
    for j in range(n):
      if(DataArray1[j,i] == 0):
        count +=1
    col.append(count)
    if(col[np.argmin(col)] == 0):
      col[np.argmin(col)] = 100
  row = []
  for i in range(n):
    count = 0
    for j in range(n):
      if(DataArray1[i,j] == 0):
        count +=1
    row.append(count)
    if(row[np.argmin(row)] == 0):
      row[np.argmin(row)] = 100
  if(np.min(col) <= np.min(row)):
    result[np.argmin(DataArray1[:,np.argmin(col)]),np.argmin(col)] = 1  # np.argmin(col) ==> 0~3열중 2열, np.argmin(DataArray1[:,np.argmin(col)])==> 2열중 0이 가장 작은 0행
    # ==> 커버한 열과 행을 1로 대체 (0을 삭제)
    DataArray1[np.argmin(DataArray1[:,np.argmin(col)]),:] = 1
    DataArray1[:,np.argmin(col)] = 1
  else:
    result[np.argmin(row), np.argmin(DataArray1[np.argmin(row),:])] = 1 # np.argmin(row) # 0~3행 중 1행, np.argmin(DataArray1[np.argmin(row),:]) # 1행중 1열

    DataArray1[np.argmin(row),:] = 1 
    DataArray1[:,np.argmin(DataArray1[np.argmin(row),:])] =1