<a href="https://colab.research.google.com/github/Junhyuck123/Production-control/blob/main/Final_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import lib

In [ ]:
import numpy as np
import pandas as pd
from scipy.optimize import linear_sum_assignment

# AP - 헝가리안 모델

In [ ]:
n = int(input())

4


In [ ]:
c = np.random.randint(1, 15, size = (n, n))
cost = pd.DataFrame(c)
cost

0  1   2   3
0  4  4   3   1
1  6  1   3  13
2  7  8  13   3
3  5  6   6  10

In [ ]:
# c_m = np.array([[9,6,3,4],
#                 [5,8,12,10],
#                 [2,6,7,4],
#                 [4,11,13,7]])

# cost = pd.DataFrame(c_m)
# cost

In [ ]:
stack_c = pd.DataFrame()
for i in range(n):
  col = np.array(cost[i])
  col_min = min(col)
  col = col - col_min
  col = pd.DataFrame(col)
  stack_c[i] = col
stack_c

0  1   2   3
0  0  3   0   0
1  2  0   0  12
2  3  7  10   2
3  1  5   3   9

In [ ]:
pre_Data = pd.DataFrame()
for i in range(n):
  row = stack_c.iloc[i][:]
  row_min = min(row)
  row = row - row_min
  row = pd.DataFrame(row)
  pre_Data[i] = row
pre_Data = pre_Data.transpose()
pre_Data

0  1  2   3
0  0  3  0   0
1  2  0  0  12
2  1  5  8   0
3  0  4  2   8

In [ ]:
pre_Data1 = pd.DataFrame()
pre_Data1 = pre_Data.copy()
del_row_lst = [] # 삭제한 행 목록
del_col_lst = [] # 삭제한 열 목록
row_cnt = 0 # 행에서 0의 갯수
col_cnt = 0 # 열에서 0의 갯수
cnt = 0 # For 루프 시행 횟수
pre_Data1

0  1  2   3
0  0  3  0   0
1  2  0  0  12
2  1  5  8   0
3  0  4  2   8

In [ ]:
for d in range(n): # n matrix의 경우 n번 시행
  print("---------------{}번째 시행---------------".format(d))

  #ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
  count_col = 0
  count_col_lst = []
  for i in range(len(pre_Data1.columns)):
    for j in range(len(pre_Data1.index)):
      if(pre_Data1.iloc[j][i] == 0):
        count_col += 1

    count_col_lst.append(int(count_col))
    print('col의 0의 수 : {}'.format(count_col_lst))
    count_col = 0
  #ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
  count_row = 0 # col의 index별 0의갯수 초기화
  count_row_lst = [] # 열 별 0의 갯수 저장
  for i in range(len(pre_Data1.index)):
    for j in range(len(pre_Data1.columns)): # 열과 행의 갯수 만큼 for 문 실행 (삭제하며 찾기 때문에 n이 아닌 len루프)
      if(pre_Data1.iloc[i][j] == 0): 
        count_row += 1

    count_row_lst.append(int(count_row))
    print('row의 0의 수 : {}'.format(count_row_lst))
    count_row = 0


  #ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

  
  # Zero 개수의 최대값 index를 저장하는 리스트
  col_zero_index = [i for i, value in enumerate(count_col_lst) if value == np.max(count_col_lst)]
  row_zero_index = [i for i, value in enumerate(count_row_lst) if value == np.max(count_row_lst)]

  #ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
  # 행을 삭제할지 열을 삭제할지 결정
  choice = []
  choice.append(int(np.max(count_col_lst)))
  choice.append(int(np.max(count_row_lst)))
  choice = int(np.argmax(choice)) # 같은 숫자일 경우 행을 삭제
  print('col의 0의 수 Max값 : {}'.format(np.max(count_col_lst)))
  print('row의 0의 수 Max값 : {}'.format(np.max(count_row_lst)))
  
  print(pre_Data1)


  if(choice == 0): #어떤 행 Or 열을 커버하는지 Print하기 위한 
    choice_str = "열"
  else:
    choice_str = "행"
  print('커버 할 행 또는 열 선택 : {0}'.format(choice_str))  # 단순 출력

  if(choice == 0): # 행을 선택한 경우 삭제
    del_col_lst.append(col_zero_index[0])
    pre_Data1 = pre_Data1.drop(columns=col_zero_index[0])
  else: #열을 선택한 경우
    del_row_lst.append(row_zero_index[0])
    pre_Data1 = pre_Data1.drop(row_zero_index[0], axis='columns')

  pre_Data1= pd.DataFrame(np.array(pre_Data1)) #DataFrame형태로 재변환 (1열을 삭제할 경우 index가 0 2 3 으로 처리 --> for문에서 오류발생)
  cnt += 1





if(cnt != 4): # 커버하는 선의 수가 4개 이하인 경우 아래 셀 추가 실행
  print("아래 항목을 실행하세요")

---------------0번째 시행---------------
col의 0의 수 : [2]
col의 0의 수 : [2, 1]
col의 0의 수 : [2, 1, 2]
col의 0의 수 : [2, 1, 2, 2]
row의 0의 수 : [3]
row의 0의 수 : [3, 2]
row의 0의 수 : [3, 2, 1]
row의 0의 수 : [3, 2, 1, 1]
col의 0의 수 Max값 : 2
row의 0의 수 Max값 : 3
   0  1  2   3
0  0  3  0   0
1  2  0  0  12
2  1  5  8   0
3  0  4  2   8
커버 할 행 또는 열 선택 : 행
---------------1번째 시행---------------
col의 0의 수 : [1]
col의 0의 수 : [1, 2]
col의 0의 수 : [1, 2, 2]
row의 0의 수 : [2]
row의 0의 수 : [2, 2]
row의 0의 수 : [2, 2, 1]
row의 0의 수 : [2, 2, 1, 0]
col의 0의 수 Max값 : 2
row의 0의 수 Max값 : 2
   0  1   2
0  3  0   0
1  0  0  12
2  5  8   0
3  4  2   8
커버 할 행 또는 열 선택 : 열
---------------2번째 시행---------------
col의 0의 수 : [1]
col의 0의 수 : [1, 2]
row의 0의 수 : [1]
row의 0의 수 : [1, 1]
row의 0의 수 : [1, 1, 1]
row의 0의 수 : [1, 1, 1, 0]
col의 0의 수 Max값 : 2
row의 0의 수 Max값 : 1
   0   1
0  3   0
1  0  12
2  5   0
3  4   8
커버 할 행 또는 열 선택 : 열
---------------3번째 시행---------------
col의 0의 수 : [1]
row의 0의 수 : [0]
row의 0의 수 : [0, 1]
row의 0의 수 : [0, 1, 0]
row의 0의 

In [ ]:
# ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
 
# 커버한 열 또는 행의 index를 저장하는 문장
num = list(range(n))
del_row_index = []
del_col_index = []

for i in range(len(del_col_lst)): 
  del_col_index.append(num[del_col_lst[i]])
  del num[del_col_lst[i]]

num = list(range(n))

for i in range(len(del_row_lst)):
  del_row_index.append(num[del_row_lst[i]])
  del num[del_row_lst[i]]
# ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

In [ ]:
del_row_index, del_col_index

([0], [1, 2, 0])

In [ ]:
pre_Data

0  1  2   3
0  0  3  0   0
1  2  0  0  12
2  1  5  8   0
3  0  4  2   8

### cnt != n
**커버한 선의 수가 맞지 않을경우**
**셀 실행 이후위 알고리즘 재실행**

In [ ]:
Data_Array = np.array(pre_Data)

In [ ]:
if(cnt != n):
  num = list(range(n))
  plus_row = list(set(num)-set(del_row_index))

#커버된 INDEX, 중복된 INDEX, 커버하지 않은 INDEX를 각각 저장 이후 계산해줌
  Cross_matrix = np.random.randint(0, 1, size = (n, n))
  double_Cross_matrix = np.random.randint(0, 1, size = (n, n))
  Not_cov_matrix = np.random.randint(1, 2, size = (n, n))
  for i in range(len(del_row_index)):
    Not_cov_matrix[del_row_index[i]] = 0
    for j in range(len(del_col_index)):
      Cross_matrix[del_row_index[i]][del_col_index[j]] = 1
      for k in range(len(plus_row)):
        Not_cov_matrix[plus_row[k]][del_col_index[j]] = 0
        double_Cross_matrix[plus_row[k]][del_col_index[j]] = 1
  Not_cov_matrix_val = np.multiply(Data_Array, Not_cov_matrix)
  min_val = np.min(Not_cov_matrix_val[Not_cov_matrix_val!=0])


  pre_Data = pd.DataFrame(Data_Array - min_val * Not_cov_matrix + min_val*Cross_matrix + min_val * double_Cross_matrix)

In [ ]:
count_col = 0
count_col_lst = []
for i in range(len(pre_Data.columns)):
  for j in range(len(pre_Data.index)):
    if(pre_Data.iloc[j][i] == 0):
      count_col += 1

  count_col_lst.append(int(count_col))
  print('col의 0의 수 : {}'.format(count_col_lst))
  count_col = 0
#ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
count_row = 0 # col의 index별 0의갯수 초기화
count_row_lst = [] # 열 별 0의 갯수 저장
for i in range(len(pre_Data.index)):
  for j in range(len(pre_Data.columns)): # 열과 행의 갯수 만큼 for 문 실행 (삭제하며 찾기 때문에 n이 아닌 len루프)
    if(pre_Data.iloc[i][j] == 0): 
      count_row += 1

  count_row_lst.append(int(count_row))
  print('row의 0의 수 : {}'.format(count_row_lst))
  count_row = 0


col의 0의 수 : [2]
col의 0의 수 : [2, 1]
col의 0의 수 : [2, 1, 2]
col의 0의 수 : [2, 1, 2, 2]
row의 0의 수 : [3]
row의 0의 수 : [3, 2]
row의 0의 수 : [3, 2, 1]
row의 0의 수 : [3, 2, 1, 1]


In [ ]:
count_col_lst , count_row_lst

([2, 1, 2, 2], [3, 2, 1, 1])

# 결과 뽑기 시각화

In [ ]:
DataArray = np.array(pre_Data)
col = []
for i in range(n):
  count = 0
  for j in range(n):
    if(DataArray[j,i] == 0):
      count +=1
  col.append(count)

row = []
for i in range(n):
  count = 0
  for j in range(n):
    if(DataArray[i,j] == 0):
      count +=1
  row.append(count)

In [ ]:
DataArray1 = DataArray
result = np.zeros([n,n])
DataArray1

array([[ 0,  3,  0,  0],
       [ 2,  0,  0, 12],
       [ 1,  5,  8,  0],
       [ 0,  4,  2,  8]])

In [ ]:
if(np.min(col) <= np.min(row)):
  result[np.argmin(DataArray1[:,np.argmin(col)]),np.argmin(col)] = 1  # np.argmin(col) ==> 0~3열중 2열, np.argmin(DataArray1[:,np.argmin(col)])==> 2열중 0이 가장 작은 0행
  # ==> 커버한 열과 행을 1로 대체 (0을 삭제)
  DataArray1[np.argmin(DataArray1[:,np.argmin(col)]),:] = 1
  DataArray1[:,np.argmin(col)] = 1
else:
  result[np.argmin(row), np.argmin(DataArray1[np.argmin(row),:])] = 1 # np.argmin(row) # 0~3행 중 1행, np.argmin(DataArray1[np.argmin(row),:]) # 1행중 1열

  DataArray1[np.argmin(row),:] = 1 
  DataArray1[:,np.argmin(DataArray1[np.argmin(row),:])] =1

In [ ]:
result

array([[0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
col = []
for i in range(n):
  count = 0
  for j in range(n):
    if(DataArray1[j,i] == 0):
      count +=1
  col.append(count)
  if(col[np.argmin(col)] == 0):
    col[np.argmin(col)] = 100
row = []
for i in range(n):
  count = 0
  for j in range(n):
    if(DataArray1[i,j] == 0):
      count +=1
  row.append(count)
  if(row[np.argmin(row)] == 0):
    row[np.argmin(row)] = 100

In [ ]:
if(np.min(col) <= np.min(row)):
  result[np.argmin(DataArray1[:,np.argmin(col)]),np.argmin(col)] = 1  # np.argmin(col) ==> 0~3열중 2열, np.argmin(DataArray1[:,np.argmin(col)])==> 2열중 0이 가장 작은 0행
  # ==> 커버한 열과 행을 1로 대체 (0을 삭제)
  DataArray1[np.argmin(DataArray1[:,np.argmin(col)]),:] = 1
  DataArray1[:,np.argmin(col)] = 1
else:
  result[np.argmin(row), np.argmin(DataArray1[np.argmin(row),:])] = 1 # np.argmin(row) # 0~3행 중 1행, np.argmin(DataArray1[np.argmin(row),:]) # 1행중 1열

  DataArray1[np.argmin(row),:] = 1 
  DataArray1[:,np.argmin(DataArray1[np.argmin(row),:])] =1

In [ ]:
result

array([[0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
col = []
for i in range(n):
  count = 0
  for j in range(n):
    if(DataArray1[j,i] == 0):
      count +=1
  col.append(count)
  if(col[np.argmin(col)] == 0):
    col[np.argmin(col)] = 100
row = []
for i in range(n):
  count = 0
  for j in range(n):
    if(DataArray1[i,j] == 0):
      count +=1
  row.append(count)
  if(row[np.argmin(row)] == 0):
    row[np.argmin(row)] = 100

In [ ]:
if(np.min(col) <= np.min(row)):
  result[np.argmin(DataArray1[:,np.argmin(col)]),np.argmin(col)] = 1  # np.argmin(col) ==> 0~3열중 2열, np.argmin(DataArray1[:,np.argmin(col)])==> 2열중 0이 가장 작은 0행
  # ==> 커버한 열과 행을 1로 대체 (0을 삭제)
  DataArray1[np.argmin(DataArray1[:,np.argmin(col)]),:] = 1
  DataArray1[:,np.argmin(col)] = 1
else:
  result[np.argmin(row), np.argmin(DataArray1[np.argmin(row),:])] = 1 # np.argmin(row) # 0~3행 중 1행, np.argmin(DataArray1[np.argmin(row),:]) # 1행중 1열

  DataArray1[np.argmin(row),:] = 1 
  DataArray1[:,np.argmin(DataArray1[np.argmin(row),:])] =1

In [ ]:
result

array([[0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [ ]:
col = []
for i in range(n):
  count = 0
  for j in range(n):
    if(DataArray1[j,i] == 0):
      count +=1
  col.append(count)
  if(col[np.argmin(col)] == 0):
    col[np.argmin(col)] = 100
row = []
for i in range(n):
  count = 0
  for j in range(n):
    if(DataArray1[i,j] == 0):
      count +=1
  row.append(count)
  if(row[np.argmin(row)] == 0):
    row[np.argmin(row)] = 100

In [ ]:
if(np.min(col) <= np.min(row)):
  result[np.argmin(DataArray1[:,np.argmin(col)]),np.argmin(col)] = 1  # np.argmin(col) ==> 0~3열중 2열, np.argmin(DataArray1[:,np.argmin(col)])==> 2열중 0이 가장 작은 0행
  # ==> 커버한 열과 행을 1로 대체 (0을 삭제)
  DataArray1[np.argmin(DataArray1[:,np.argmin(col)]),:] = 1
  DataArray1[:,np.argmin(col)] = 1
else:
  result[np.argmin(row), np.argmin(DataArray1[np.argmin(row),:])] = 1 # np.argmin(row) # 0~3행 중 1행, np.argmin(DataArray1[np.argmin(row),:]) # 1행중 1열

  DataArray1[np.argmin(row),:] = 1 
  DataArray1[:,np.argmin(DataArray1[np.argmin(row),:])] =1

In [ ]:
result

array([[0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.]])

In [ ]:
Total_Cost = np.multiply(np.array(cost), result).sum()
Total_Cost

12.0

# 결과 한번에 뽑기

In [ ]:
DataArray = np.array(pre_Data)
col = []
for i in range(n):
  count = 0
  for j in range(n):
    if(DataArray[j,i] == 0):
      count +=1
  col.append(count)

row = []
for i in range(n):
  count = 0
  for j in range(n):
    if(DataArray[i,j] == 0):
      count +=1
  row.append(count)

In [ ]:
DataArray1 = DataArray
result = np.zeros([n,n])
DataArray1

array([[ 0,  3,  0,  0],
       [ 2,  0,  0, 12],
       [ 1,  5,  8,  0],
       [ 0,  4,  2,  8]])

In [ ]:
if(np.min(col) <= np.min(row)):
  result[np.argmin(DataArray1[:,np.argmin(col)]),np.argmin(col)] = 1  # np.argmin(col) ==> 0~3열중 2열, np.argmin(DataArray1[:,np.argmin(col)])==> 2열중 0이 가장 작은 0행
  # ==> 커버한 열과 행을 1로 대체 (0을 삭제)
  DataArray1[np.argmin(DataArray1[:,np.argmin(col)]),:] = 1
  DataArray1[:,np.argmin(col)] = 1
else:
  result[np.argmin(row), np.argmin(DataArray1[np.argmin(row),:])] = 1 # np.argmin(row) # 0~3행 중 1행, np.argmin(DataArray1[np.argmin(row),:]) # 1행중 1열

  DataArray1[np.argmin(row),:] = 1 
  DataArray1[:,np.argmin(DataArray1[np.argmin(row),:])] =1

In [ ]:
for k in range(n-1):
  col = []
  for i in range(n):
    count = 0
    for j in range(n):
      if(DataArray1[j,i] == 0):
        count +=1
    col.append(count)
    if(col[np.argmin(col)] == 0):
      col[np.argmin(col)] = 100
  row = []
  for i in range(n):
    count = 0
    for j in range(n):
      if(DataArray1[i,j] == 0):
        count +=1
    row.append(count)
    if(row[np.argmin(row)] == 0):
      row[np.argmin(row)] = 100
  if(np.min(col) <= np.min(row)):
    result[np.argmin(DataArray1[:,np.argmin(col)]),np.argmin(col)] = 1  # np.argmin(col) ==> 0~3열중 2열, np.argmin(DataArray1[:,np.argmin(col)])==> 2열중 0이 가장 작은 0행
    # ==> 커버한 열과 행을 1로 대체 (0을 삭제)
    DataArray1[np.argmin(DataArray1[:,np.argmin(col)]),:] = 1
    DataArray1[:,np.argmin(col)] = 1
  else:
    result[np.argmin(row), np.argmin(DataArray1[np.argmin(row),:])] = 1 # np.argmin(row) # 0~3행 중 1행, np.argmin(DataArray1[np.argmin(row),:]) # 1행중 1열

    DataArray1[np.argmin(row),:] = 1 
    DataArray1[:,np.argmin(DataArray1[np.argmin(row),:])] =1

In [ ]:
Total_Cost = np.multiply(np.array(cost), result).sum()
Total_Cost

12.0

# AP - LP

In [ ]:
c_m = np.array(cost)
row_ind, col_ind = linear_sum_assignment(c_m)
opt_ass = col_ind
tc = c_m[row_ind, col_ind].sum()


print(c_m)
print(opt_ass)
print(tc)

[[ 4  4  3  1]
 [ 6  1  3 13]
 [ 7  8 13  3]
 [ 5  6  6 10]]
[2 1 3 0]
12
